# Generated by Django 6.0 on 2025-12-28 18:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Addmoney_info",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "add_money",
                    models.CharField(
                        choices=[("Expense", "Expense"), ("Income", "Income")],
                        max_length=255,
                    ),
                ),
                ("date", models.DateField(default=django.utils.timezone.now)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Food", "Food"),
                            ("Travel", "Travel"),
                            ("Shopping", "Shopping"),
                            ("Necessities", "Necessities"),
                            ("Entertainment", "Entertainment"),
                            ("Other", "other"),
                        ],
                        default="Food",
                        max_length=255,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "addmoney",
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "profession",
                    models.CharField(
                        choices=[
                            ("Employee", "Employee"),
                            ("Business", "Business"),
                            ("Student", "Student"),
                            ("Other", "Other"),
                        ],
                        max_length=255,
                    ),
                ),
                ("savings", models.IntegerField(blank=True, null=True)),
                ("income", models.BigIntegerField(blank=True, null=True)),
                ("image", models.ImageField(blank=True, upload_to="profile_image")),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
