# Generated by Django 6.0 on 2025-12-28 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="addmoney_info",
            name="quantity",
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="addmoney_info",
            name="category",
            field=models.CharField(
                choices=[
                    ("Food", "Food"),
                    ("Travel", "Travel"),
                    ("Shopping", "Shopping"),
                    ("Necessities", "Necessities"),
                    ("Entertainment", "Entertainment"),
                    ("Other", "Other"),
                ],
                default="Food",
                max_length=255,
            ),
        ),
    ]
