# Generated by Django 6.0 on 2025-12-30 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_addmoney_info_quantity_alter_addmoney_info_category"),
    ]

    operations = [
        migrations.RenameField(
            model_name="addmoney_info",
            old_name="quantity",
            new_name="amount",
        ),
        migrations.AddField(
            model_name="addmoney_info",
            name="description",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="addmoney_info",
            name="category",
            field=models.CharField(
                choices=[
                    ("Groceries", "Groceries"),
                    ("Shopping", "Shopping"),
                    ("Rent", "Rent"),
                    ("Internet", "Internet"),
                    ("Savings", "Savings"),
                    ("Laundry", "Laundry"),
                    ("Outing", "Outing"),
                    ("Necessities", "Necessities"),
                    ("Other", "Other"),
                ],
                default="Food",
                max_length=255,
            ),
        ),
    ]
