# Generated by Django 6.0 on 2025-12-31 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_rename_quantity_addmoney_info_amount_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="profession",
        ),
    ]
