# Generated by Django 6.0 on 2026-01-03 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_remove_userprofile_profession"),
    ]

    operations = [
        migrations.AlterField(
            model_name="addmoney_info",
            name="category",
            field=models.CharField(
                choices=[
                    ("Groceries", "Groceries"),
                    ("Shopping", "Shopping"),
                    ("Rent", "Rent"),
                    ("Internet", "Internet"),
                    ("Medicines", "Medicines"),
                    ("Savings", "Savings"),
                    ("Laundry", "Laundry"),
                    ("Outing", "Outing"),
                    ("Necessities", "Necessities"),
                    ("Other", "Other"),
                ],
                default="Food",
                max_length=255,
            ),
        ),
    ]
