# Generated by Django 6.0 on 2026-01-03 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_alter_addmoney_info_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="addmoney_info",
            name="category",
            field=models.CharField(default="", max_length=255),
        ),
    ]
